#!/bin/bash
executable   = run_analysis.sh
universe     = vanilla
output       = /home/jmsardain/CalibPU/Resample/MakeJets/SendJobs/logfiles/job_$(ClusterId)_analysis.out
error        = /home/jmsardain/CalibPU/Resample/MakeJets/SendJobs/logfiles/job_$(ClusterId)_analysis.err
log          = /home/jmsardain/CalibPU/Resample/MakeJets/SendJobs/logfiles/job_$(ClusterId)_analysis.log
request_memory = 50GB
+JobFlavour  = "nextweek"

queue