#define MakeJets_cxx
#include "MakeJets.h"
#include <TH2.h>
#include <TStyle.h>
#include <TCanvas.h>
#include <iostream>

void MakeJets::Loop(TString JZSlice){
   
   TFile* fout = TFile::Open("/data/jmsardain/CalibPU/datasets/pu/JetTree_"+JZSlice+".root", "RECREATE");
   TTree* tout = new TTree("JetTree", "One entry per jet");

   float out_LCWJetMatchRadius;
   float out_areaRho;
   int out_eventNumber;
   float out_jetArea;
   float out_jetAreaE;
   float out_jetAreaEta;
   float out_jetAreaFM;
   float out_jetAreaM;
   float out_jetAreaPhi;
   float out_jetAreaPt;
   float out_jetCalE;
   float out_jetCalEta;
   float out_jetCalM;
   float out_jetCalPhi;
   float out_jetCalPt;
   int out_jetCnt;
   float out_jetNConst;
   float out_jetRawE;
   float out_jetRawEta;
   float out_jetRawM;
   float out_jetRawPhi;
   float out_jetRawPt;
   float out_matchedLCWJetRawE;
   float out_matchedLCWJetRawM;
   float out_matchedLCWJetRawPhi;
   float out_matchedLCWJetRawPt;
   float out_matchedLCWJetRawRap;
   float out_medianRho;
   float out_nCluster;
   float out_runNumber;
   float out_seqNumber;
   float out_sigmaRho;
   float out_truthJetE;
   float out_truthJetM;
   float out_truthJetMatchRadius;
   float out_truthJetPhi;
   float out_truthJetPt;
   float out_truthJetRap;

   std::vector<float> out_avgMu;
   std::vector<float> out_clusterE;
   std::vector<float> out_clusterECalib;
   std::vector<float> out_clusterEta;
   std::vector<float> out_clusterEtaCalib;
   std::vector<float> out_clusterIndex;
   std::vector<float> out_clusterPhi;
   std::vector<float> out_clusterPhiCalib;
   std::vector<float> out_clusterPt;
   std::vector<float> out_clusterPtCalib;
   std::vector<float> out_cluster_AVG_LAR_Q;
   std::vector<float> out_cluster_AVG_TILE_Q;
   std::vector<float> out_cluster_BADLARQ_FRAC;
   std::vector<float> out_cluster_BAD_CELLS_CORR_E;
   std::vector<float> out_cluster_CELL_SIGNIFICANCE;
   std::vector<float> out_cluster_CELL_SIG_SAMPLING;
   std::vector<float> out_cluster_CENTER_LAMBDA;
   std::vector<float> out_cluster_CENTER_MAG;
   std::vector<float> out_cluster_CENTER_X;
   std::vector<float> out_cluster_CENTER_Y;
   std::vector<float> out_cluster_CENTER_Z;
   std::vector<float> out_cluster_DELTA_ALPHA;
   std::vector<float> out_cluster_DELTA_PHI;
   std::vector<float> out_cluster_DELTA_THETA;
   std::vector<float> out_cluster_DM_WEIGHT;
   std::vector<float> out_cluster_EM_PROBABILITY;
   std::vector<float> out_cluster_ENG_BAD_CELLS;
   std::vector<float> out_cluster_ENG_BAD_HV_CELLS;
   std::vector<float> out_cluster_ENG_CALIB_DEAD_TOT;
   std::vector<float> out_cluster_ENG_CALIB_FRAC_EM;
   std::vector<float> out_cluster_ENG_CALIB_FRAC_HAD;
   std::vector<float> out_cluster_ENG_CALIB_FRAC_REST;
   std::vector<float> out_cluster_ENG_CALIB_OUT_L;
   std::vector<float> out_cluster_ENG_CALIB_OUT_M;
   std::vector<float> out_cluster_ENG_CALIB_OUT_T;
   std::vector<float> out_cluster_ENG_CALIB_TOT;
   std::vector<float> out_cluster_ENG_FRAC_CORE;
   std::vector<float> out_cluster_ENG_FRAC_EM;
   std::vector<float> out_cluster_ENG_FRAC_EM_INCL;
   std::vector<float> out_cluster_ENG_FRAC_MAX;
   std::vector<float> out_cluster_ENG_POS;
   std::vector<float> out_cluster_FIRST_ENG_DENS;
   std::vector<float> out_cluster_FIRST_ETA;
   std::vector<float> out_cluster_FIRST_PHI;
   std::vector<float> out_cluster_HAD_WEIGHT;
   std::vector<float> out_cluster_ISOLATION;
   std::vector<float> out_cluster_LATERAL;
   std::vector<float> out_cluster_LONGITUDINAL;
   std::vector<float> out_cluster_MASS;
   std::vector<float> out_cluster_N_BAD_CELLS;
   std::vector<float> out_cluster_N_BAD_CELLS_CORR;
   std::vector<float> out_cluster_N_BAD_HV_CELLS;
   std::vector<float> out_cluster_OOC_WEIGHT;
   std::vector<float> out_cluster_PTD;
   std::vector<float> out_cluster_SECOND_ENG_DENS;
   std::vector<float> out_cluster_SECOND_LAMBDA;
   std::vector<float> out_cluster_SECOND_R;
   std::vector<float> out_cluster_SECOND_TIME;
   std::vector<float> out_cluster_SIGNIFICANCE;
   std::vector<float> out_cluster_fracE;
   std::vector<float> out_cluster_fracECalib;
   std::vector<float> out_cluster_fracECalib_ref;
   std::vector<float> out_cluster_fracE_ref;
   std::vector<float> out_cluster_nCells;
   std::vector<float> out_cluster_nCells_tot;
   std::vector<float> out_cluster_sumCellE;
   std::vector<float> out_cluster_sumCellECalib;
   std::vector<float> out_cluster_time;
   std::vector<float> out_diffEta;
   std::vector<int> out_labels;
   std::vector<int> out_nPrimVtx;
   std::vector<float> out_r_e_calculated;
   std::vector<float> out_zL;
   std::vector<float> out_zRel;
   std::vector<float> out_zT;

   tout->Branch("LCWJetMatchRadius", &out_LCWJetMatchRadius);
   tout->Branch("areaRho", &out_areaRho);
   tout->Branch("eventNumber", &out_eventNumber);
   tout->Branch("jetArea", &out_jetArea);
   tout->Branch("jetAreaE", &out_jetAreaE);
   tout->Branch("jetAreaEta", &out_jetAreaEta);
   tout->Branch("jetAreaFM", &out_jetAreaFM);
   tout->Branch("jetAreaM", &out_jetAreaM);
   tout->Branch("jetAreaPhi", &out_jetAreaPhi);
   tout->Branch("jetAreaPt", &out_jetAreaPt);
   tout->Branch("jetCalE", &out_jetCalE);
   tout->Branch("jetCalEta", &out_jetCalEta);
   tout->Branch("jetCalM", &out_jetCalM);
   tout->Branch("jetCalPhi", &out_jetCalPhi);
   tout->Branch("jetCalPt", &out_jetCalPt);
   tout->Branch("jetCnt", &out_jetCnt);
   tout->Branch("jetNConst", &out_jetNConst);
   tout->Branch("jetRawE", &out_jetRawE);
   tout->Branch("jetRawEta", &out_jetRawEta);
   tout->Branch("jetRawM", &out_jetRawM);
   tout->Branch("jetRawPhi", &out_jetRawPhi);
   tout->Branch("jetRawPt", &out_jetRawPt);
   tout->Branch("matchedLCWJetRawE", &out_matchedLCWJetRawE);
   tout->Branch("matchedLCWJetRawM", &out_matchedLCWJetRawM);
   tout->Branch("matchedLCWJetRawPhi", &out_matchedLCWJetRawPhi);
   tout->Branch("matchedLCWJetRawPt", &out_matchedLCWJetRawPt);
   tout->Branch("matchedLCWJetRawRap", &out_matchedLCWJetRawRap);
   tout->Branch("medianRho", &out_medianRho);
   tout->Branch("nCluster", &out_nCluster);
   tout->Branch("runNumber", &out_runNumber);
   tout->Branch("seqNumber", &out_seqNumber);
   tout->Branch("sigmaRho", &out_sigmaRho);
   tout->Branch("truthJetE", &out_truthJetE);
   tout->Branch("truthJetM", &out_truthJetM);
   tout->Branch("truthJetMatchRadius", &out_truthJetMatchRadius);
   tout->Branch("truthJetPhi", &out_truthJetPhi);
   tout->Branch("truthJetPt", &out_truthJetPt);
   tout->Branch("truthJetRap", &out_truthJetRap);

   tout->Branch("avgMu", &out_avgMu);
   tout->Branch("clusterE", &out_clusterE);
   tout->Branch("clusterECalib", &out_clusterECalib);
   tout->Branch("clusterEta", &out_clusterEta);
   tout->Branch("clusterEtaCalib", &out_clusterEtaCalib);
   tout->Branch("clusterIndex", &out_clusterIndex);
   tout->Branch("clusterPhi", &out_clusterPhi);
   tout->Branch("clusterPhiCalib", &out_clusterPhiCalib);
   tout->Branch("clusterPt", &out_clusterPt);
   tout->Branch("clusterPtCalib", &out_clusterPtCalib);
   tout->Branch("cluster_AVG_LAR_Q", &out_cluster_AVG_LAR_Q);
   tout->Branch("cluster_AVG_TILE_Q", &out_cluster_AVG_TILE_Q);
   tout->Branch("cluster_BADLARQ_FRAC", &out_cluster_BADLARQ_FRAC);
   tout->Branch("cluster_BAD_CELLS_CORR_E", &out_cluster_BAD_CELLS_CORR_E);
   tout->Branch("cluster_CELL_SIGNIFICANCE", &out_cluster_CELL_SIGNIFICANCE);
   tout->Branch("cluster_CELL_SIG_SAMPLING", &out_cluster_CELL_SIG_SAMPLING);
   tout->Branch("cluster_CENTER_LAMBDA", &out_cluster_CENTER_LAMBDA);
   tout->Branch("cluster_CENTER_MAG", &out_cluster_CENTER_MAG);
   tout->Branch("cluster_CENTER_X", &out_cluster_CENTER_X);
   tout->Branch("cluster_CENTER_Y", &out_cluster_CENTER_Y);
   tout->Branch("cluster_CENTER_Z", &out_cluster_CENTER_Z);
   tout->Branch("cluster_DELTA_ALPHA", &out_cluster_DELTA_ALPHA);
   tout->Branch("cluster_DELTA_PHI", &out_cluster_DELTA_PHI);
   tout->Branch("cluster_DELTA_THETA", &out_cluster_DELTA_THETA);
   tout->Branch("cluster_DM_WEIGHT", &out_cluster_DM_WEIGHT);
   tout->Branch("cluster_EM_PROBABILITY", &out_cluster_EM_PROBABILITY);
   tout->Branch("cluster_ENG_BAD_CELLS", &out_cluster_ENG_BAD_CELLS);
   tout->Branch("cluster_ENG_BAD_HV_CELLS", &out_cluster_ENG_BAD_HV_CELLS);
   tout->Branch("cluster_ENG_CALIB_DEAD_TOT", &out_cluster_ENG_CALIB_DEAD_TOT);
   tout->Branch("cluster_ENG_CALIB_FRAC_EM", &out_cluster_ENG_CALIB_FRAC_EM);
   tout->Branch("cluster_ENG_CALIB_FRAC_HAD", &out_cluster_ENG_CALIB_FRAC_HAD);
   tout->Branch("cluster_ENG_CALIB_FRAC_REST", &out_cluster_ENG_CALIB_FRAC_REST);
   tout->Branch("cluster_ENG_CALIB_OUT_L", &out_cluster_ENG_CALIB_OUT_L);
   tout->Branch("cluster_ENG_CALIB_OUT_M", &out_cluster_ENG_CALIB_OUT_M);
   tout->Branch("cluster_ENG_CALIB_OUT_T", &out_cluster_ENG_CALIB_OUT_T);
   tout->Branch("cluster_ENG_CALIB_TOT", &out_cluster_ENG_CALIB_TOT);
   tout->Branch("cluster_ENG_FRAC_CORE", &out_cluster_ENG_FRAC_CORE);
   tout->Branch("cluster_ENG_FRAC_EM", &out_cluster_ENG_FRAC_EM);
   tout->Branch("cluster_ENG_FRAC_EM_INCL", &out_cluster_ENG_FRAC_EM_INCL);
   tout->Branch("cluster_ENG_FRAC_MAX", &out_cluster_ENG_FRAC_MAX);
   tout->Branch("cluster_ENG_POS", &out_cluster_ENG_POS);
   tout->Branch("cluster_FIRST_ENG_DENS", &out_cluster_FIRST_ENG_DENS);
   tout->Branch("cluster_FIRST_ETA", &out_cluster_FIRST_ETA);
   tout->Branch("cluster_FIRST_PHI", &out_cluster_FIRST_PHI);
   tout->Branch("cluster_HAD_WEIGHT", &out_cluster_HAD_WEIGHT);
   tout->Branch("cluster_ISOLATION", &out_cluster_ISOLATION);
   tout->Branch("cluster_LATERAL", &out_cluster_LATERAL);
   tout->Branch("cluster_LONGITUDINAL", &out_cluster_LONGITUDINAL);
   tout->Branch("cluster_MASS", &out_cluster_MASS);
   tout->Branch("cluster_N_BAD_CELLS", &out_cluster_N_BAD_CELLS);
   tout->Branch("cluster_N_BAD_CELLS_CORR", &out_cluster_N_BAD_CELLS_CORR);
   tout->Branch("cluster_N_BAD_HV_CELLS", &out_cluster_N_BAD_HV_CELLS);
   tout->Branch("cluster_OOC_WEIGHT", &out_cluster_OOC_WEIGHT);
   tout->Branch("cluster_PTD", &out_cluster_PTD);
   tout->Branch("cluster_SECOND_ENG_DENS", &out_cluster_SECOND_ENG_DENS);
   tout->Branch("cluster_SECOND_LAMBDA", &out_cluster_SECOND_LAMBDA);
   tout->Branch("cluster_SECOND_R", &out_cluster_SECOND_R);
   tout->Branch("cluster_SECOND_TIME", &out_cluster_SECOND_TIME);
   tout->Branch("cluster_SIGNIFICANCE", &out_cluster_SIGNIFICANCE);
   tout->Branch("cluster_fracE", &out_cluster_fracE);
   tout->Branch("cluster_fracECalib", &out_cluster_fracECalib);
   tout->Branch("cluster_fracECalib_ref", &out_cluster_fracECalib_ref);
   tout->Branch("cluster_fracE_ref", &out_cluster_fracE_ref);
   tout->Branch("cluster_nCells", &out_cluster_nCells);
   tout->Branch("cluster_nCells_tot", &out_cluster_nCells_tot);
   tout->Branch("cluster_sumCellE", &out_cluster_sumCellE);
   tout->Branch("cluster_sumCellECalib", &out_cluster_sumCellECalib);
   tout->Branch("cluster_time", &out_cluster_time);
   tout->Branch("diffEta", &out_diffEta);
   tout->Branch("labels", &out_labels);
   tout->Branch("nPrimVtx", &out_nPrimVtx);
   tout->Branch("r_e_calculated", &out_r_e_calculated);
   tout->Branch("zL", &out_zL);
   tout->Branch("zRel", &out_zRel);
   tout->Branch("zT", &out_zT);


   if (fChain == 0) return;

   Long64_t nentries = fChain->GetEntriesFast();

   Long64_t prev_event = -1;
   Long64_t prev_jet   = -1;

   Long64_t nbytes = 0, nb = 0;
   for (Long64_t jentry=0; jentry<nentries;jentry++) {
      Long64_t ientry = LoadTree(jentry);
      if (ientry < 0) break;
      nb = fChain->GetEntry(jentry);   nbytes += nb;
      // if (Cut(ientry) < 0) continue;
      if (jentry%100000==0) {std::cout << " Entry #" << jentry << std::endl; }
      
      bool newJet = (eventNumber != prev_event) || (jetCnt != prev_jet);

      if (newJet && jentry > 0) {
         // Flush previous jet
         tout->Fill();

         // Clear vectors (CRITICAL)
         out_avgMu.clear();
         out_clusterE.clear();
         out_clusterECalib.clear();
         out_clusterEta.clear();
         out_clusterEtaCalib.clear();
         out_clusterIndex.clear();
         out_clusterPhi.clear();
         out_clusterPhiCalib.clear();
         out_clusterPt.clear();
         out_clusterPtCalib.clear();
         out_cluster_AVG_LAR_Q.clear();
         out_cluster_AVG_TILE_Q.clear();
         out_cluster_BADLARQ_FRAC.clear();
         out_cluster_BAD_CELLS_CORR_E.clear();
         out_cluster_CELL_SIGNIFICANCE.clear();
         out_cluster_CELL_SIG_SAMPLING.clear();
         out_cluster_CENTER_LAMBDA.clear();
         out_cluster_CENTER_MAG.clear();
         out_cluster_CENTER_X.clear();
         out_cluster_CENTER_Y.clear();
         out_cluster_CENTER_Z.clear();
         out_cluster_DELTA_ALPHA.clear();
         out_cluster_DELTA_PHI.clear();
         out_cluster_DELTA_THETA.clear();
         out_cluster_DM_WEIGHT.clear();
         out_cluster_EM_PROBABILITY.clear();
         out_cluster_ENG_BAD_CELLS.clear();
         out_cluster_ENG_BAD_HV_CELLS.clear();
         out_cluster_ENG_CALIB_DEAD_TOT.clear();
         out_cluster_ENG_CALIB_FRAC_EM.clear();
         out_cluster_ENG_CALIB_FRAC_HAD.clear();
         out_cluster_ENG_CALIB_FRAC_REST.clear();
         out_cluster_ENG_CALIB_OUT_L.clear();
         out_cluster_ENG_CALIB_OUT_M.clear();
         out_cluster_ENG_CALIB_OUT_T.clear();
         out_cluster_ENG_CALIB_TOT.clear();
         out_cluster_ENG_FRAC_CORE.clear();
         out_cluster_ENG_FRAC_EM.clear();
         out_cluster_ENG_FRAC_EM_INCL.clear();
         out_cluster_ENG_FRAC_MAX.clear();
         out_cluster_ENG_POS.clear();
         out_cluster_FIRST_ENG_DENS.clear();
         out_cluster_FIRST_ETA.clear();
         out_cluster_FIRST_PHI.clear();
         out_cluster_HAD_WEIGHT.clear();
         out_cluster_ISOLATION.clear();
         out_cluster_LATERAL.clear();
         out_cluster_LONGITUDINAL.clear();
         out_cluster_MASS.clear();
         out_cluster_N_BAD_CELLS.clear();
         out_cluster_N_BAD_CELLS_CORR.clear();
         out_cluster_N_BAD_HV_CELLS.clear();
         out_cluster_OOC_WEIGHT.clear();
         out_cluster_PTD.clear();
         out_cluster_SECOND_ENG_DENS.clear();
         out_cluster_SECOND_LAMBDA.clear();
         out_cluster_SECOND_R.clear();
         out_cluster_SECOND_TIME.clear();
         out_cluster_SIGNIFICANCE.clear();
         out_cluster_fracE.clear();
         out_cluster_fracECalib.clear();
         out_cluster_fracECalib_ref.clear();
         out_cluster_fracE_ref.clear();
         out_cluster_nCells.clear();
         out_cluster_nCells_tot.clear();
         out_cluster_sumCellE.clear();
         out_cluster_sumCellECalib.clear();
         out_cluster_time.clear();
         out_diffEta.clear();
         out_labels.clear();
         out_nPrimVtx.clear();
         out_r_e_calculated.clear();
         out_zL.clear();
         out_zRel.clear();
         out_zT.clear();
      }

      if (newJet) {
         out_LCWJetMatchRadius = LCWJetMatchRadius;
         out_areaRho = areaRho;
         out_eventNumber = eventNumber;
         out_jetArea = jetArea;
         out_jetAreaE = jetAreaE;
         out_jetAreaEta = jetAreaEta;
         out_jetAreaFM = jetAreaFM;
         out_jetAreaM = jetAreaM;
         out_jetAreaPhi = jetAreaPhi;
         out_jetAreaPt = jetAreaPt;
         out_jetCalE = jetCalE;
         out_jetCalEta = jetCalEta;
         out_jetCalM = jetCalM;
         out_jetCalPhi = jetCalPhi;
         out_jetCalPt = jetCalPt;
         out_jetCnt = jetCnt;
         out_jetNConst = jetNConst;
         out_jetRawE = jetRawE;
         out_jetRawEta = jetRawEta;
         out_jetRawM = jetRawM;
         out_jetRawPhi = jetRawPhi;
         out_jetRawPt = jetRawPt;
         out_matchedLCWJetRawE = matchedLCWJetRawE;
         out_matchedLCWJetRawM = matchedLCWJetRawM;
         out_matchedLCWJetRawPhi = matchedLCWJetRawPhi;
         out_matchedLCWJetRawPt = matchedLCWJetRawPt;
         out_matchedLCWJetRawRap = matchedLCWJetRawRap;
         out_medianRho = medianRho;
         out_nCluster = nCluster;
         out_runNumber = runNumber;
         out_seqNumber = seqNumber;
         out_sigmaRho = sigmaRho;
         out_truthJetE = truthJetE;
         out_truthJetM = truthJetM;
         out_truthJetMatchRadius = truthJetMatchRadius;
         out_truthJetPhi = truthJetPhi;
         out_truthJetPt = truthJetPt;
         out_truthJetRap = truthJetRap;
      }

      out_avgMu.push_back(avgMu);
      out_clusterE.push_back(clusterE);
      out_clusterECalib.push_back(clusterECalib);
      out_clusterEta.push_back(clusterEta);
      out_clusterEtaCalib.push_back(clusterEtaCalib);
      out_clusterIndex.push_back(clusterIndex);
      out_clusterPhi.push_back(clusterPhi);
      out_clusterPhiCalib.push_back(clusterPhiCalib);
      out_clusterPt.push_back(clusterPt);
      out_clusterPtCalib.push_back(clusterPtCalib);
      out_cluster_AVG_LAR_Q.push_back(cluster_AVG_LAR_Q);
      out_cluster_AVG_TILE_Q.push_back(cluster_AVG_TILE_Q);
      out_cluster_BADLARQ_FRAC.push_back(cluster_BADLARQ_FRAC);
      out_cluster_BAD_CELLS_CORR_E.push_back(cluster_BAD_CELLS_CORR_E);
      out_cluster_CELL_SIGNIFICANCE.push_back(cluster_CELL_SIGNIFICANCE);
      out_cluster_CELL_SIG_SAMPLING.push_back(cluster_CELL_SIG_SAMPLING);
      out_cluster_CENTER_LAMBDA.push_back(cluster_CENTER_LAMBDA);
      out_cluster_CENTER_MAG.push_back(cluster_CENTER_MAG);
      out_cluster_CENTER_X.push_back(cluster_CENTER_X);
      out_cluster_CENTER_Y.push_back(cluster_CENTER_Y);
      out_cluster_CENTER_Z.push_back(cluster_CENTER_Z);
      out_cluster_DELTA_ALPHA.push_back(cluster_DELTA_ALPHA);
      out_cluster_DELTA_PHI.push_back(cluster_DELTA_PHI);
      out_cluster_DELTA_THETA.push_back(cluster_DELTA_THETA);
      out_cluster_DM_WEIGHT.push_back(cluster_DM_WEIGHT);
      out_cluster_EM_PROBABILITY.push_back(cluster_EM_PROBABILITY);
      out_cluster_ENG_BAD_CELLS.push_back(cluster_ENG_BAD_CELLS);
      out_cluster_ENG_BAD_HV_CELLS.push_back(cluster_ENG_BAD_HV_CELLS);
      out_cluster_ENG_CALIB_DEAD_TOT.push_back(cluster_ENG_CALIB_DEAD_TOT);
      out_cluster_ENG_CALIB_FRAC_EM.push_back(cluster_ENG_CALIB_FRAC_EM);
      out_cluster_ENG_CALIB_FRAC_HAD.push_back(cluster_ENG_CALIB_FRAC_HAD);
      out_cluster_ENG_CALIB_FRAC_REST.push_back(cluster_ENG_CALIB_FRAC_REST);
      out_cluster_ENG_CALIB_OUT_L.push_back(cluster_ENG_CALIB_OUT_L);
      out_cluster_ENG_CALIB_OUT_M.push_back(cluster_ENG_CALIB_OUT_M);
      out_cluster_ENG_CALIB_OUT_T.push_back(cluster_ENG_CALIB_OUT_T);
      out_cluster_ENG_CALIB_TOT.push_back(cluster_ENG_CALIB_TOT);
      out_cluster_ENG_FRAC_CORE.push_back(cluster_ENG_FRAC_CORE);
      out_cluster_ENG_FRAC_EM.push_back(cluster_ENG_FRAC_EM);
      out_cluster_ENG_FRAC_EM_INCL.push_back(cluster_ENG_FRAC_EM_INCL);
      out_cluster_ENG_FRAC_MAX.push_back(cluster_ENG_FRAC_MAX);
      out_cluster_ENG_POS.push_back(cluster_ENG_POS);
      out_cluster_FIRST_ENG_DENS.push_back(cluster_FIRST_ENG_DENS);
      out_cluster_FIRST_ETA.push_back(cluster_FIRST_ETA);
      out_cluster_FIRST_PHI.push_back(cluster_FIRST_PHI);
      out_cluster_HAD_WEIGHT.push_back(cluster_HAD_WEIGHT);
      out_cluster_ISOLATION.push_back(cluster_ISOLATION);
      out_cluster_LATERAL.push_back(cluster_LATERAL);
      out_cluster_LONGITUDINAL.push_back(cluster_LONGITUDINAL);
      out_cluster_MASS.push_back(cluster_MASS);
      out_cluster_N_BAD_CELLS.push_back(cluster_N_BAD_CELLS);
      out_cluster_N_BAD_CELLS_CORR.push_back(cluster_N_BAD_CELLS_CORR);
      out_cluster_N_BAD_HV_CELLS.push_back(cluster_N_BAD_HV_CELLS);
      out_cluster_OOC_WEIGHT.push_back(cluster_OOC_WEIGHT);
      out_cluster_PTD.push_back(cluster_PTD);
      out_cluster_SECOND_ENG_DENS.push_back(cluster_SECOND_ENG_DENS);
      out_cluster_SECOND_LAMBDA.push_back(cluster_SECOND_LAMBDA);
      out_cluster_SECOND_R.push_back(cluster_SECOND_R);
      out_cluster_SECOND_TIME.push_back(cluster_SECOND_TIME);
      out_cluster_SIGNIFICANCE.push_back(cluster_SIGNIFICANCE);
      out_cluster_fracE.push_back(cluster_fracE);
      out_cluster_fracECalib.push_back(cluster_fracECalib);
      out_cluster_fracECalib_ref.push_back(cluster_fracECalib_ref);
      out_cluster_fracE_ref.push_back(cluster_fracE_ref);
      out_cluster_nCells.push_back(cluster_nCells);
      out_cluster_nCells_tot.push_back(cluster_nCells_tot);
      out_cluster_sumCellE.push_back(cluster_sumCellE);
      out_cluster_sumCellECalib.push_back(cluster_sumCellECalib);
      out_cluster_time.push_back(cluster_time);
      out_diffEta.push_back(diffEta);
      out_labels.push_back(labels);
      out_nPrimVtx.push_back(nPrimVtx);
      out_r_e_calculated.push_back(r_e_calculated);
      out_zL.push_back(zL);
      out_zRel.push_back(zRel);
      out_zT.push_back(zT);

      prev_event = eventNumber;
      prev_jet = jetCnt;
   }

   if (!out_clusterE.empty()) {
      tout->Fill();
   }

   fout->Write();
   fout->Close();

   std::cout << "Done. Jets written for " << JZSlice << std::endl;
}
